# Generated by Django 5.2.9 on 2026-03-05 15:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerryGoRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cycle_duration_weeks', models.PositiveIntegerField(default=1)),
                ('payout_order_type', models.CharField(choices=[('manual', 'Manual'), ('random', 'Random')], default='manual', max_length=10)),
                ('payout_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=10)),
                ('payouts_per_period', models.PositiveIntegerField(default=1)),
                ('next_payout_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MerryContributionDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(db_index=True, max_length=20)),
                ('slot_no', models.PositiveIntegerField()),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='merry.merrygoround')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MerryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='merry.merrygoround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merry_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MerryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_phone', models.CharField(db_index=True, max_length=20)),
                ('period_key', models.CharField(db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='merry.merrymember')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merry_payments_initiated', to=settings.AUTH_USER_MODEL)),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='merry.merrygoround')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MerryPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='merry.merrycontributiondue')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='merry.merrypayment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MerrySeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.PositiveIntegerField()),
                ('payout_position', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='merry.merrymember')),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='merry.merrygoround')),
            ],
            options={
                'ordering': ['payout_position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MerryPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(db_index=True, max_length=20)),
                ('slot_no', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='merry.merrygoround')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='merry.merryseat')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='merrycontributiondue',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='merry.merryseat'),
        ),
        migrations.CreateModel(
            name='MerrySlotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_no', models.PositiveIntegerField()),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_configs', to='merry.merrygoround')),
            ],
            options={
                'ordering': ['slot_no'],
            },
        ),
        migrations.CreateModel(
            name='MerryJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_seats', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='merry.merrygoround')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_merry_join_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merry_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='merry_merry_status_b0d02f_idx')],
                'constraints': [models.UniqueConstraint(fields=('merry', 'user'), name='uniq_join_request_per_merry_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='merrymember',
            constraint=models.UniqueConstraint(fields=('merry', 'user'), name='uniq_user_per_merry'),
        ),
        migrations.AddIndex(
            model_name='merrypayment',
            index=models.Index(fields=['status', 'created_at'], name='merry_merry_status_5e0a08_idx'),
        ),
        migrations.AddIndex(
            model_name='merrypayment',
            index=models.Index(fields=['mpesa_receipt_number'], name='merry_merry_mpesa_r_089cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='merrypayment',
            index=models.Index(fields=['payer_phone', 'created_at'], name='merry_merry_payer_p_430e32_idx'),
        ),
        migrations.AddConstraint(
            model_name='merrypaymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'due'), name='uniq_allocation_per_payment_due'),
        ),
        migrations.AddConstraint(
            model_name='merryseat',
            constraint=models.UniqueConstraint(fields=('member', 'seat_no'), name='uniq_seat_no_per_member'),
        ),
        migrations.AddConstraint(
            model_name='merryseat',
            constraint=models.UniqueConstraint(fields=('merry', 'payout_position'), name='uniq_payout_position_per_merry_seat'),
        ),
        migrations.AddIndex(
            model_name='merrypayout',
            index=models.Index(fields=['period_key', 'created_at'], name='merry_merry_period__d5496d_idx'),
        ),
        migrations.AddIndex(
            model_name='merrypayout',
            index=models.Index(fields=['slot_no', 'created_at'], name='merry_merry_slot_no_9ffacf_idx'),
        ),
        migrations.AddConstraint(
            model_name='merrypayout',
            constraint=models.UniqueConstraint(fields=('merry', 'period_key', 'slot_no'), name='uniq_payout_per_period_slot'),
        ),
        migrations.AddConstraint(
            model_name='merrypayout',
            constraint=models.UniqueConstraint(fields=('merry', 'seat', 'period_key'), name='uniq_seat_payout_per_period'),
        ),
        migrations.AddIndex(
            model_name='merrycontributiondue',
            index=models.Index(fields=['period_key', 'slot_no'], name='merry_merry_period__515f37_idx'),
        ),
        migrations.AddIndex(
            model_name='merrycontributiondue',
            index=models.Index(fields=['status', 'updated_at'], name='merry_merry_status_438a0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='merrycontributiondue',
            constraint=models.UniqueConstraint(fields=('seat', 'period_key', 'slot_no'), name='uniq_due_per_seat_period_slot'),
        ),
        migrations.AddConstraint(
            model_name='merryslotconfig',
            constraint=models.UniqueConstraint(fields=('merry', 'slot_no'), name='uniq_slot_config_per_merry'),
        ),
    ]
