# Generated by Django 5.2.9 on 2026-03-28 01:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerryGoRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cycle_duration_weeks', models.PositiveIntegerField(default=1)),
                ('payout_order_type', models.CharField(choices=[('manual', 'Manual'), ('random', 'Random')], default='manual', max_length=10)),
                ('payout_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=10)),
                ('payouts_per_period', models.PositiveIntegerField(default=1)),
                ('is_open', models.BooleanField(default=True)),
                ('max_seats', models.PositiveIntegerField(default=0, help_text='0 means unlimited seats')),
                ('next_payout_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MerryContributionDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(db_index=True, max_length=20)),
                ('slot_no', models.PositiveIntegerField()),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('OVERDUE', 'Overdue'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_advance_payable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='merry.merrygoround')),
            ],
            options={
                'ordering': ['due_date', 'slot_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MerryJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_seats', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='merry.merrygoround')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_merry_join_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merry_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MerryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='merry.merrygoround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merry_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MerryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_phone', models.CharField(db_index=True, max_length=20)),
                ('period_key', models.CharField(db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='merry.merrymember')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merry_payments_initiated', to=settings.AUTH_USER_MODEL)),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='merry.merrygoround')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MerryPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='merry.merrycontributiondue')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='merry.merrypayment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MerrySeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.PositiveIntegerField()),
                ('payout_position', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='merry.merrymember')),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='merry.merrygoround')),
            ],
            options={
                'ordering': ['seat_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MerryPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(db_index=True, max_length=20)),
                ('slot_no', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='merry.merrygoround')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='merry.merryseat')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='merrycontributiondue',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='merry.merryseat'),
        ),
        migrations.CreateModel(
            name='MerrySlotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_no', models.PositiveIntegerField()),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_configs', to='merry.merrygoround')),
            ],
            options={
                'ordering': ['slot_no'],
            },
        ),
        migrations.CreateModel(
            name='MerryWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merry_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merry Wallet',
                'verbose_name_plural': 'Merry Wallets',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='MerryWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('narration', models.CharField(blank=True, default='', max_length=255)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merry_wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='merry.merrywallet')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='merrygoround',
            index=models.Index(fields=['is_open', 'created_at'], name='merry_merry_is_open_8d2d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='merrygoround',
            index=models.Index(fields=['payout_frequency', 'created_at'], name='merry_merry_payout__afa7df_idx'),
        ),
        migrations.AddIndex(
            model_name='merryjoinrequest',
            index=models.Index(fields=['merry', 'status', 'created_at'], name='merry_merry_merry_i_812636_idx'),
        ),
        migrations.AddIndex(
            model_name='merryjoinrequest',
            index=models.Index(fields=['user', 'status', 'created_at'], name='merry_merry_user_id_f2dcdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='merryjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('merry', 'user'), name='uniq_pending_join_request_per_merry_user'),
        ),
        migrations.AddIndex(
            model_name='merrymember',
            index=models.Index(fields=['user', 'is_active'], name='merry_merry_user_id_944e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='merrymember',
            index=models.Index(fields=['merry', 'is_active'], name='merry_merry_merry_i_882f44_idx'),
        ),
        migrations.AddConstraint(
            model_name='merrymember',
            constraint=models.UniqueConstraint(fields=('merry', 'user'), name='uniq_user_per_merry'),
        ),
        migrations.AddIndex(
            model_name='merrypayment',
            index=models.Index(fields=['merry', 'status', 'created_at'], name='merry_merry_merry_i_79d0d0_idx'),
        ),
        migrations.AddIndex(
            model_name='merrypayment',
            index=models.Index(fields=['beneficiary_member', 'created_at'], name='merry_merry_benefic_7fb337_idx'),
        ),
        migrations.AddIndex(
            model_name='merrypayment',
            index=models.Index(fields=['mpesa_receipt_number'], name='merry_merry_mpesa_r_089cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='merrypayment',
            index=models.Index(fields=['payer_phone', 'created_at'], name='merry_merry_payer_p_430e32_idx'),
        ),
        migrations.AddConstraint(
            model_name='merrypaymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'due'), name='uniq_allocation_per_payment_due'),
        ),
        migrations.AddIndex(
            model_name='merryseat',
            index=models.Index(fields=['merry', 'is_active'], name='merry_merry_merry_i_bff89a_idx'),
        ),
        migrations.AddIndex(
            model_name='merryseat',
            index=models.Index(fields=['member', 'is_active'], name='merry_merry_member__7192c8_idx'),
        ),
        migrations.AddIndex(
            model_name='merryseat',
            index=models.Index(fields=['merry', 'seat_no'], name='merry_merry_merry_i_712d3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='merryseat',
            constraint=models.UniqueConstraint(fields=('merry', 'seat_no'), name='uniq_seat_no_per_merry'),
        ),
        migrations.AddConstraint(
            model_name='merryseat',
            constraint=models.UniqueConstraint(condition=models.Q(('payout_position__isnull', False)), fields=('merry', 'payout_position'), name='uniq_payout_position_per_merry_seat'),
        ),
        migrations.AddIndex(
            model_name='merrypayout',
            index=models.Index(fields=['merry', 'period_key', 'slot_no'], name='merry_merry_merry_i_2348cc_idx'),
        ),
        migrations.AddIndex(
            model_name='merrypayout',
            index=models.Index(fields=['status', 'created_at'], name='merry_merry_status_de49d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='merrypayout',
            constraint=models.UniqueConstraint(fields=('merry', 'period_key', 'slot_no'), name='uniq_payout_per_period_slot'),
        ),
        migrations.AddConstraint(
            model_name='merrypayout',
            constraint=models.UniqueConstraint(fields=('merry', 'seat', 'period_key'), name='uniq_seat_payout_per_period'),
        ),
        migrations.AddIndex(
            model_name='merrycontributiondue',
            index=models.Index(fields=['merry', 'period_key', 'slot_no'], name='merry_merry_merry_i_a4be9d_idx'),
        ),
        migrations.AddIndex(
            model_name='merrycontributiondue',
            index=models.Index(fields=['status', 'updated_at'], name='merry_merry_status_438a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='merrycontributiondue',
            index=models.Index(fields=['due_date', 'status'], name='merry_merry_due_dat_b3ccd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='merrycontributiondue',
            constraint=models.UniqueConstraint(fields=('seat', 'period_key', 'slot_no'), name='uniq_due_per_seat_period_slot'),
        ),
        migrations.AddConstraint(
            model_name='merryslotconfig',
            constraint=models.UniqueConstraint(fields=('merry', 'slot_no'), name='uniq_slot_config_per_merry'),
        ),
        migrations.AddIndex(
            model_name='merrywallet',
            index=models.Index(fields=['user'], name='merry_merry_user_id_0020c3_idx'),
        ),
        migrations.AddIndex(
            model_name='merrywallet',
            index=models.Index(fields=['updated_at'], name='merry_merry_updated_fb8ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='merrywallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='merry_merry_wallet__e8176f_idx'),
        ),
        migrations.AddIndex(
            model_name='merrywallettransaction',
            index=models.Index(fields=['user', 'created_at'], name='merry_merry_user_id_0a4683_idx'),
        ),
        migrations.AddIndex(
            model_name='merrywallettransaction',
            index=models.Index(fields=['tx_type', 'created_at'], name='merry_merry_tx_type_e8e279_idx'),
        ),
        migrations.AddIndex(
            model_name='merrywallettransaction',
            index=models.Index(fields=['reference'], name='merry_merry_referen_bfef4e_idx'),
        ),
        migrations.AddIndex(
            model_name='merrywallettransaction',
            index=models.Index(fields=['mpesa_receipt_number'], name='merry_merry_mpesa_r_db84a7_idx'),
        ),
    ]
