# Generated by Django 5.2.9 on 2026-03-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merrygoround',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merrygoround',
            name='max_seats',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited seats'),
        ),
    ]
