# Generated by Django 5.2.9 on 2026-03-03 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='contribution',
        ),
        migrations.RemoveField(
            model_name='member',
            name='merry',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='member',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='merry',
        ),
        migrations.AlterModelOptions(
            name='merrygoround',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='merrygoround',
            name='next_payout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merrygoround',
            name='contribution_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='merrygoround',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='merrygoround',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='merrygoround',
            name='cycle_duration_weeks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='merrygoround',
            name='payout_order_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('random', 'Random')], default='manual', max_length=10),
        ),
        migrations.CreateModel(
            name='MerryJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='merry.merrygoround')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_merry_join_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merry_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MerryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_position', models.PositiveIntegerField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='merry.merrygoround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merry_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MerryContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='merry.merrymember')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MerryPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='merry.merrymember')),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='merry.merrygoround')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Payout',
        ),
        migrations.AddIndex(
            model_name='merryjoinrequest',
            index=models.Index(fields=['status', 'created_at'], name='merry_merry_status_b0d02f_idx'),
        ),
        migrations.AddConstraint(
            model_name='merryjoinrequest',
            constraint=models.UniqueConstraint(fields=('merry', 'user'), name='uniq_join_request_per_merry_user'),
        ),
        migrations.AddConstraint(
            model_name='merrymember',
            constraint=models.UniqueConstraint(fields=('merry', 'user'), name='uniq_user_per_merry'),
        ),
        migrations.AddConstraint(
            model_name='merrymember',
            constraint=models.UniqueConstraint(fields=('merry', 'payout_position'), name='uniq_payout_position_per_merry'),
        ),
        migrations.AddIndex(
            model_name='merrycontribution',
            index=models.Index(fields=['status', 'created_at'], name='merry_merry_status_a3ed6d_idx'),
        ),
        migrations.AddIndex(
            model_name='merrycontribution',
            index=models.Index(fields=['week_number'], name='merry_merry_week_nu_65a21b_idx'),
        ),
        migrations.AddConstraint(
            model_name='merrycontribution',
            constraint=models.UniqueConstraint(fields=('member', 'week_number'), name='uniq_merry_contribution_per_week'),
        ),
        migrations.AddConstraint(
            model_name='merrypayout',
            constraint=models.UniqueConstraint(fields=('merry', 'week_number'), name='uniq_payout_per_merry_week'),
        ),
        migrations.AddConstraint(
            model_name='merrypayout',
            constraint=models.UniqueConstraint(fields=('merry', 'member', 'week_number'), name='uniq_member_payout_per_week'),
        ),
    ]
