# Generated by Django 5.2.9 on 2026-04-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merrycontributiondue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('OVERDUE', 'Overdue'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='merryjoinrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='merrypayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='merrypayout',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=50),
        ),
    ]
