# Generated by Django 5.2.9 on 2026-06-13 15:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merrypayment',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='merrypayment',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
