# Generated by Django 5.2.9 on 2026-04-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merry', '0002_alter_merrycontributiondue_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merrypayment',
            name='payer_phone',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
