# Generated by Django 5.2.9 on 2026-03-11 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merry', '0002_merrygoround_is_open_merrygoround_max_seats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merryseat',
            options={'ordering': ['seat_no', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='merryjoinrequest',
            name='uniq_join_request_per_merry_user',
        ),
        migrations.RemoveConstraint(
            model_name='merryseat',
            name='uniq_seat_no_per_member',
        ),
        migrations.RemoveConstraint(
            model_name='merryseat',
            name='uniq_payout_position_per_merry_seat',
        ),
        migrations.RemoveIndex(
            model_name='merrycontributiondue',
            name='merry_merry_period__515f37_idx',
        ),
        migrations.RemoveIndex(
            model_name='merryjoinrequest',
            name='merry_merry_status_b0d02f_idx',
        ),
        migrations.RemoveIndex(
            model_name='merrypayment',
            name='merry_merry_status_5e0a08_idx',
        ),
        migrations.RemoveIndex(
            model_name='merrypayout',
            name='merry_merry_period__d5496d_idx',
        ),
        migrations.RemoveIndex(
            model_name='merrypayout',
            name='merry_merry_slot_no_9ffacf_idx',
        ),
        migrations.AddIndex(
            model_name='merrycontributiondue',
            index=models.Index(fields=['merry', 'period_key', 'slot_no'], name='merry_merry_merry_i_a4be9d_idx'),
        ),
        migrations.AddIndex(
            model_name='merrygoround',
            index=models.Index(fields=['is_open', 'created_at'], name='merry_merry_is_open_8d2d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='merrygoround',
            index=models.Index(fields=['payout_frequency', 'created_at'], name='merry_merry_payout__afa7df_idx'),
        ),
        migrations.AddIndex(
            model_name='merryjoinrequest',
            index=models.Index(fields=['merry', 'status', 'created_at'], name='merry_merry_merry_i_812636_idx'),
        ),
        migrations.AddIndex(
            model_name='merryjoinrequest',
            index=models.Index(fields=['user', 'status', 'created_at'], name='merry_merry_user_id_f2dcdc_idx'),
        ),
        migrations.AddIndex(
            model_name='merrymember',
            index=models.Index(fields=['user', 'is_active'], name='merry_merry_user_id_944e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='merrymember',
            index=models.Index(fields=['merry', 'is_active'], name='merry_merry_merry_i_882f44_idx'),
        ),
        migrations.AddIndex(
            model_name='merrypayment',
            index=models.Index(fields=['merry', 'status', 'created_at'], name='merry_merry_merry_i_79d0d0_idx'),
        ),
        migrations.AddIndex(
            model_name='merrypayment',
            index=models.Index(fields=['beneficiary_member', 'created_at'], name='merry_merry_benefic_7fb337_idx'),
        ),
        migrations.AddIndex(
            model_name='merrypayout',
            index=models.Index(fields=['merry', 'period_key', 'slot_no'], name='merry_merry_merry_i_2348cc_idx'),
        ),
        migrations.AddIndex(
            model_name='merrypayout',
            index=models.Index(fields=['status', 'created_at'], name='merry_merry_status_de49d1_idx'),
        ),
        migrations.AddIndex(
            model_name='merryseat',
            index=models.Index(fields=['merry', 'is_active'], name='merry_merry_merry_i_bff89a_idx'),
        ),
        migrations.AddIndex(
            model_name='merryseat',
            index=models.Index(fields=['member', 'is_active'], name='merry_merry_member__7192c8_idx'),
        ),
        migrations.AddIndex(
            model_name='merryseat',
            index=models.Index(fields=['merry', 'seat_no'], name='merry_merry_merry_i_712d3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='merryjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('merry', 'user'), name='uniq_pending_join_request_per_merry_user'),
        ),
        migrations.AddConstraint(
            model_name='merryseat',
            constraint=models.UniqueConstraint(fields=('merry', 'seat_no'), name='uniq_seat_no_per_merry'),
        ),
        migrations.AddConstraint(
            model_name='merryseat',
            constraint=models.UniqueConstraint(condition=models.Q(('payout_position__isnull', False)), fields=('merry', 'payout_position'), name='uniq_payout_position_per_merry_seat'),
        ),
    ]
