# Generated by Django 5.2.9 on 2026-04-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merry', '0003_alter_merrypayment_payer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merrycontributiondue',
            name='is_advance_payable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='merrycontributiondue',
            name='slot_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='merrygoround',
            name='payout_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=10),
        ),
    ]
