# Generated by Django 5.2.9 on 2026-03-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merry', '0003_alter_merryseat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merrycontributiondue',
            options={'ordering': ['due_date', 'slot_no', 'id']},
        ),
        migrations.AddField(
            model_name='merrycontributiondue',
            name='is_advance_payable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='merrycontributiondue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('OVERDUE', 'Overdue'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='merrycontributiondue',
            index=models.Index(fields=['due_date', 'status'], name='merry_merry_due_dat_b3ccd7_idx'),
        ),
    ]
