# Generated by Django 5.2.9 on 2026-03-20 18:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merry', '0004_alter_merrycontributiondue_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerryWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merry_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merry Wallet',
                'verbose_name_plural': 'Merry Wallets',
                'ordering': ['user_id'],
                'indexes': [models.Index(fields=['user'], name='merry_merry_user_id_0020c3_idx'), models.Index(fields=['updated_at'], name='merry_merry_updated_fb8ed1_idx')],
            },
        ),
        migrations.CreateModel(
            name='MerryWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('narration', models.CharField(blank=True, default='', max_length=255)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merry_wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='merry_merry_user_id_0a4683_idx'), models.Index(fields=['tx_type', 'created_at'], name='merry_merry_tx_type_e8e279_idx'), models.Index(fields=['reference'], name='merry_merry_referen_bfef4e_idx'), models.Index(fields=['mpesa_receipt_number'], name='merry_merry_mpesa_r_db84a7_idx')],
            },
        ),
    ]
