# Generated by Django 5.2.9 on 2026-04-17 10:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merry', '0004_alter_merrycontributiondue_is_advance_payable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merrypayout',
            options={'ordering': ['turn_no', 'id']},
        ),
        migrations.AddField(
            model_name='merrycontributiondue',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='merrycontributiondue',
            name='days_overdue',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merrycontributiondue',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='merry.merrypayout'),
        ),
        migrations.AddField(
            model_name='merrycontributiondue',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='merrycontributiondue',
            name='penalty_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merrycontributiondue',
            name='penalty_last_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merrygoround',
            name='daily_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='merrygoround',
            name='flat_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='merrygoround',
            name='penalty_cap_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional max total penalty per due.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='merrygoround',
            name='penalty_grace_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merrygoround',
            name='penalty_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('FLAT', 'Flat'), ('DAILY', 'Daily')], default='NONE', help_text='NONE, FLAT, or DAILY', max_length=10),
        ),
        migrations.AddField(
            model_name='merrypayout',
            name='cycle_no',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='merrypayout',
            name='scheduled_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='merrypayout',
            name='turn_no',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddIndex(
            model_name='merrycontributiondue',
            index=models.Index(fields=['merry', 'payout'], name='merry_merry_merry_i_762cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='merrycontributiondue',
            index=models.Index(fields=['days_overdue', 'status'], name='merry_merry_days_ov_527485_idx'),
        ),
        migrations.AddIndex(
            model_name='merrygoround',
            index=models.Index(fields=['penalty_mode', 'created_at'], name='merry_merry_penalty_4d8c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='merrypayout',
            index=models.Index(fields=['merry', 'turn_no'], name='merry_merry_merry_i_10ccd9_idx'),
        ),
        migrations.AddIndex(
            model_name='merrypayout',
            index=models.Index(fields=['merry', 'cycle_no', 'turn_no'], name='merry_merry_merry_i_7960f6_idx'),
        ),
        migrations.AddIndex(
            model_name='merrypayout',
            index=models.Index(fields=['merry', 'scheduled_date'], name='merry_merry_merry_i_a9030f_idx'),
        ),
        migrations.AddConstraint(
            model_name='merrycontributiondue',
            constraint=models.UniqueConstraint(condition=models.Q(('payout__isnull', False)), fields=('seat', 'payout'), name='uniq_due_per_seat_per_payout'),
        ),
        migrations.AddConstraint(
            model_name='merrypayout',
            constraint=models.UniqueConstraint(fields=('merry', 'turn_no'), name='uniq_payout_turn_no_per_merry'),
        ),
    ]
