# Generated by Django 5.2.9 on 2026-03-22 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merry', '0005_merrywallet_merrywallettransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merrywallettransaction',
            name='wallet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='merry.merrywallet'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='merrywallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='merry_merry_wallet__e8176f_idx'),
        ),
    ]
