# Generated by Django 5.2.9 on 2026-04-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merry', '0006_backfill_turn_linked_rosca'),
    ]

    operations = [
        migrations.AddField(
            model_name='merrygoround',
            name='payout_days',
            field=models.JSONField(default=list),
        ),
    ]
