# Generated by Django 5.2.9 on 2026-04-26 19:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_groupdependant'),
        ('merry', '0001_initial'),
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interest_type', models.CharField(choices=[('FLAT', 'Flat'), ('REDUCING', 'Reducing Balance')], default='FLAT', max_length=20)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('repayment_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=10)),
                ('repayment_weekday', models.IntegerField(default=0)),
                ('max_weeks', models.PositiveIntegerField(default=12)),
                ('late_fee_rate_weekly', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Percentage charged weekly on overdue installment total_due (e.g. 2.00 = 2%)', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Used when member requests a loan without choosing a product.')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term_weeks', models.PositiveIntegerField(default=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('is_defaulter', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('security_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('security_reserved_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('member_note', models.TextField(blank=True, default='')),
                ('admin_note', models.TextField(blank=True, default='')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.loanproduct')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('reserved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('request_note', models.CharField(blank=True, default='', max_length=255)),
                ('admin_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loans.loan')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('loan', 'guarantor')},
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(default='MANUAL', max_length=50)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanSecurityAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('BORROWER_SAVINGS', 'Borrower Savings'), ('BORROWER_GROUP_SHARE', 'Borrower Group Share'), ('BORROWER_MERRY_CREDIT', 'Borrower Merry Credit'), ('GUARANTOR_SAVINGS', 'Guarantor Savings'), ('GUARANTOR_GROUP_SHARE', 'Guarantor Group Share'), ('GUARANTOR_MERRY_CREDIT', 'Guarantor Merry Credit')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_security_allocations', to='groups.group')),
                ('guarantor_link', models.ForeignKey(blank=True, help_text='Set when this allocation is tied to a guarantor on this loan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_allocations', to='loans.loanguarantor')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_allocations', to='loans.loan')),
                ('merry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_security_allocations', to='merry.merrygoround')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_security_allocations', to=settings.AUTH_USER_MODEL)),
                ('savings_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_security_allocations', to='savings.savingsaccount')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MemberCreditProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=100)),
                ('total_loans', models.IntegerField(default=0)),
                ('loans_completed', models.IntegerField(default=0)),
                ('loans_defaulted', models.IntegerField(default=0)),
                ('late_payments', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('interest_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('late_fee_weeks_applied', models.PositiveIntegerField(default=0)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.loan')),
            ],
            options={
                'ordering': ['installment_no'],
                'unique_together': {('loan', 'installment_no')},
            },
        ),
    ]
