# Generated by Django 5.2.9 on 2026-02-23 15:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interest_type', models.CharField(choices=[('FLAT', 'Flat'), ('REDUCING', 'Reducing Balance')], max_length=20)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('late_fee_rate_monthly', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=6)),
                ('max_months', models.PositiveIntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term_months', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20)),
                ('is_defaulter', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('interest_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(default='MANUAL', max_length=50)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='MemberCreditProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=100)),
                ('total_loans', models.IntegerField(default=0)),
                ('loans_completed', models.IntegerField(default=0)),
                ('loans_defaulted', models.IntegerField(default=0)),
                ('late_payments', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loans.loan')),
            ],
            options={
                'unique_together': {('loan', 'guarantor')},
            },
        ),
    ]
