# Generated by Django 5.2.9 on 2026-03-05 15:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('merry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interest_type', models.CharField(choices=[('FLAT', 'Flat'), ('REDUCING', 'Reducing Balance')], default='FLAT', max_length=20)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('repayment_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=10)),
                ('repayment_weekday', models.IntegerField(default=0)),
                ('max_weeks', models.PositiveIntegerField(default=12)),
                ('late_fee_rate_weekly', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Percentage charged weekly on overdue installment total_due (e.g., 2.00 = 2%)', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term_weeks', models.PositiveIntegerField(default=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20)),
                ('is_defaulter', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('borrower_reserved_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('borrower_reserved_merry_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('security_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='groups.group')),
                ('merry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='merry.merrygoround')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(default='MANUAL', max_length=50)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='MemberCreditProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=100)),
                ('total_loans', models.IntegerField(default=0)),
                ('loans_completed', models.IntegerField(default=0)),
                ('loans_defaulted', models.IntegerField(default=0)),
                ('late_payments', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('merry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merry.merrygoround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MerryCreditHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merry_hold', to='loans.loan')),
                ('merry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merry.merrygoround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('reserved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loans.loan')),
            ],
            options={
                'unique_together': {('loan', 'guarantor')},
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('interest_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.loan')),
            ],
            options={
                'ordering': ['installment_no'],
                'unique_together': {('loan', 'installment_no')},
            },
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('merry__isnull', False), ('group__isnull', True)), models.Q(('merry__isnull', True), ('group__isnull', False)), _connector='OR'), name='loan_exactly_one_context'),
        ),
        migrations.AddConstraint(
            model_name='membercreditprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('merry__isnull', False), ('group__isnull', True)), models.Q(('merry__isnull', True), ('group__isnull', False)), _connector='OR'), name='credit_profile_exactly_one_context'),
        ),
        migrations.AddConstraint(
            model_name='membercreditprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('merry__isnull', False)), fields=('user', 'merry'), name='uniq_credit_profile_user_merry_when_set'),
        ),
        migrations.AddConstraint(
            model_name='membercreditprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('user', 'group'), name='uniq_credit_profile_user_group_when_set'),
        ),
    ]
