# Generated by Django 5.2.9 on 2026-06-14 15:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupdependant'),
        ('loans', '0001_initial'),
        ('merry', '0002_merrypayment_gross_amount_and_more'),
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('BEFORE_DUE', 'Before Due'), ('DUE_TODAY', 'Due Today'), ('OVERDUE', 'Overdue'), ('DEFAULTED', 'Defaulted'), ('GENERAL', 'General')], max_length=20)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification'), ('WHATSAPP', 'WhatsApp'), ('MANUAL', 'Manual')], default='SMS', max_length=20)),
                ('days_remaining', models.IntegerField(default=0)),
                ('days_overdue', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('was_successful', models.BooleanField(default=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-sent_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-id'], 'verbose_name': 'Loan', 'verbose_name_plural': 'Loans'},
        ),
        migrations.AlterModelOptions(
            name='loanpayment',
            options={'ordering': ['-paid_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='loanproduct',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Loan product', 'verbose_name_plural': 'Loan products'},
        ),
        migrations.AlterModelOptions(
            name='membercreditprofile',
            options={'verbose_name': 'Member credit profile', 'verbose_name_plural': 'Member credit profiles'},
        ),
        migrations.AddField(
            model_name='loan',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='default_interest_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total default interest accumulated from overdue installments.', max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='defaulted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='late_fee_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Old late fee total. Kept for backward compatibility.', max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='normal_interest_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Normal interest charged during the agreed loan term.', max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='default_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default interest charged on unpaid installment amount only.', max_digits=12),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='default_interest_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='default_interest_weeks_applied',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='defaulted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='grace_ends_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='last_default_interest_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DUE_SOON', 'Due Soon'), ('DUE_TODAY', 'Due Today'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='applied_to_default_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='applied_to_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='applied_to_late_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='applied_to_principal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='excess_to_savings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='default_interest_rate_weekly',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Weekly default interest charged on unpaid defaulted installment amount.', max_digits=6),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=7, help_text='Days allowed after due date before default interest starts.'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('UNDER_REPAYMENT', 'Under Repayment'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='loaninstallment',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Principal plus normal interest for this installment.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='annual_interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual normal interest rate. Example: 12.00 means 12% per year.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='late_fee_rate_weekly',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Old weekly late fee rate. Kept so existing service code does not break.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='repayment_weekday',
            field=models.IntegerField(default=0, help_text='Monday=0, Tuesday=1, Wednesday=2, Thursday=3, Friday=4, Saturday=5, Sunday=6.'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower', 'status'], name='loans_loan_borrowe_d07c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'created_at'], name='loans_loan_status_59a4c3_idx'),
        ),
        migrations.AddIndex(
            model_name='loanguarantor',
            index=models.Index(fields=['guarantor', 'accepted'], name='loans_loang_guarant_aefcfd_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['loan', 'status'], name='loans_loani_loan_id_70533c_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['due_date', 'is_paid'], name='loans_loani_due_dat_ef660e_idx'),
        ),
        migrations.AddIndex(
            model_name='loanpayment',
            index=models.Index(fields=['loan', 'paid_at'], name='loans_loanp_loan_id_da9c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='loanpayment',
            index=models.Index(fields=['method', 'reference'], name='loans_loanp_method_e05f57_idx'),
        ),
        migrations.AddIndex(
            model_name='loansecurityallocation',
            index=models.Index(fields=['loan', 'is_active'], name='loans_loans_loan_id_1b4683_idx'),
        ),
        migrations.AddIndex(
            model_name='loansecurityallocation',
            index=models.Index(fields=['owner_user', 'source_type', 'is_active'], name='loans_loans_owner_u_1efcb1_idx'),
        ),
        migrations.AddField(
            model_name='loanreminderlog',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_reminder_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanreminderlog',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_logs', to='loans.loaninstallment'),
        ),
        migrations.AddField(
            model_name='loanreminderlog',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loanreminderlog',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_loan_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loanreminderlog',
            index=models.Index(fields=['loan', 'sent_at'], name='loans_loanr_loan_id_bd335f_idx'),
        ),
        migrations.AddIndex(
            model_name='loanreminderlog',
            index=models.Index(fields=['borrower', 'reminder_type'], name='loans_loanr_borrowe_da2320_idx'),
        ),
        migrations.AddIndex(
            model_name='loanreminderlog',
            index=models.Index(fields=['installment', 'reminder_type'], name='loans_loanr_install_e0b76f_idx'),
        ),
    ]
