# Generated by Django 5.2.9 on 2026-03-12 15:17

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupcontribution_groupfund_groupmembershare_and_more'),
        ('loans', '0001_initial'),
        ('merry', '0003_alter_merryseat_options_and_more'),
        ('savings', '0002_remove_withdrawrequest_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSecurityAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('BORROWER_SAVINGS', 'Borrower Savings'), ('BORROWER_GROUP_SHARE', 'Borrower Group Share'), ('BORROWER_MERRY_CREDIT', 'Borrower Merry Credit'), ('GUARANTOR_SAVINGS', 'Guarantor Savings'), ('GUARANTOR_GROUP_SHARE', 'Guarantor Group Share'), ('GUARANTOR_MERRY_CREDIT', 'Guarantor Merry Credit')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='merrycredithold',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='merrycredithold',
            name='merry',
        ),
        migrations.RemoveField(
            model_name='merrycredithold',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='loanguarantor',
            options={'ordering': ['id']},
        ),
        migrations.RemoveConstraint(
            model_name='loan',
            name='loan_exactly_one_context',
        ),
        migrations.RemoveConstraint(
            model_name='membercreditprofile',
            name='credit_profile_exactly_one_context',
        ),
        migrations.RemoveConstraint(
            model_name='membercreditprofile',
            name='uniq_credit_profile_user_merry_when_set',
        ),
        migrations.RemoveConstraint(
            model_name='membercreditprofile',
            name='uniq_credit_profile_user_group_when_set',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='borrower_reserved_merry_credit',
            new_name='security_reserved_total',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='borrower_reserved_savings',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='group',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='merry',
        ),
        migrations.RemoveField(
            model_name='membercreditprofile',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membercreditprofile',
            name='merry',
        ),
        migrations.AddField(
            model_name='loan',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='member_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='admin_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='request_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Used when member requests a loan without choosing a product.'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.loanproduct'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='late_fee_rate_weekly',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Percentage charged weekly on overdue installment total_due (e.g. 2.00 = 2%)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='membercreditprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loansecurityallocation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_security_allocations', to='groups.group'),
        ),
        migrations.AddField(
            model_name='loansecurityallocation',
            name='guarantor_link',
            field=models.ForeignKey(blank=True, help_text='Set when this allocation is tied to a guarantor on this loan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_allocations', to='loans.loanguarantor'),
        ),
        migrations.AddField(
            model_name='loansecurityallocation',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_allocations', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loansecurityallocation',
            name='merry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_security_allocations', to='merry.merrygoround'),
        ),
        migrations.AddField(
            model_name='loansecurityallocation',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_security_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loansecurityallocation',
            name='savings_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_security_allocations', to='savings.savingsaccount'),
        ),
        migrations.DeleteModel(
            name='MerryCreditHold',
        ),
    ]
