# Generated by Django 5.2.9 on 2026-02-25 12:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('loans', '0001_initial'),
        ('merry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loaninstallment',
            options={'ordering': ['installment_no']},
        ),
        migrations.RenameField(
            model_name='loanproduct',
            old_name='max_months',
            new_name='max_weeks',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='term_months',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='late_fee_rate_monthly',
        ),
        migrations.AddField(
            model_name='loan',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='groups.group'),
        ),
        migrations.AddField(
            model_name='loan',
            name='merry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='merry.merrygoround'),
        ),
        migrations.AddField(
            model_name='loan',
            name='term_weeks',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='late_fee_rate_weekly',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Percentage charged weekly on overdue installment total_due (e.g., 2.00 = 2%)', max_digits=6),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='repayment_frequency',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=10),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='repayment_weekday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membercreditprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AddField(
            model_name='membercreditprofile',
            name='merry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merry.merrygoround'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_type',
            field=models.CharField(choices=[('FLAT', 'Flat'), ('REDUCING', 'Reducing Balance')], default='FLAT', max_length=20),
        ),
        migrations.AlterField(
            model_name='membercreditprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='loaninstallment',
            unique_together={('loan', 'installment_no')},
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('merry__isnull', False), ('group__isnull', True)), models.Q(('merry__isnull', True), ('group__isnull', False)), _connector='OR'), name='loan_exactly_one_context'),
        ),
        migrations.AddConstraint(
            model_name='membercreditprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('merry__isnull', False), ('group__isnull', True)), models.Q(('merry__isnull', True), ('group__isnull', False)), _connector='OR'), name='credit_profile_exactly_one_context'),
        ),
        migrations.AddConstraint(
            model_name='membercreditprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('merry__isnull', False)), fields=('user', 'merry'), name='uniq_credit_profile_user_merry_when_set'),
        ),
        migrations.AddConstraint(
            model_name='membercreditprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('user', 'group'), name='uniq_credit_profile_user_group_when_set'),
        ),
    ]
