# Generated by Django 5.2.9 on 2026-04-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninstallment',
            name='late_fee_weeks_applied',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
