# Generated by Django 5.2.9 on 2026-03-05 15:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Kenyan number (07XXXXXXXX or 01XXXXXXXX).', regex='^(07|01)\\d{8}$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('direction', models.CharField(choices=[('IN', 'Money In'), ('OUT', 'Money Out')], default='IN', max_length=10)),
                ('channel', models.CharField(choices=[('STK', 'STK Push'), ('B2C', 'B2C Payout')], default='STK', max_length=10)),
                ('purpose', models.CharField(choices=[('SAVINGS_DEPOSIT', 'Savings Deposit'), ('MERRY_CONTRIBUTION', 'Merry Contribution'), ('GROUP_CONTRIBUTION', 'Group Contribution'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('WITHDRAWAL', 'Withdrawal'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout')], db_index=True, default='INITIATED', max_length=20)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('merchant_request_id', models.CharField(blank=True, max_length=120, null=True)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, help_text='STK unique ID returned by Safaricom (idempotency key).', max_length=120, null=True)),
                ('conversation_id', models.CharField(blank=True, db_index=True, help_text='B2C unique conversation id returned by Safaricom (idempotency key).', max_length=120, null=True)),
                ('originator_conversation_id', models.CharField(blank=True, max_length=120, null=True)),
                ('result_code', models.CharField(blank=True, max_length=20, null=True)),
                ('result_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, help_text='Receipt number for successful transactions (strongest uniqueness).', max_length=64, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('callback_payload', models.JSONField(blank=True, null=True)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ledger_posted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='Owner/user related to this transaction (if known).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Credit (Money In)'), ('DEBIT', 'Debit (Money Out)')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('SAVINGS', 'Savings'), ('LOANS', 'Loans'), ('MERRY', 'Merry-go-round'), ('GROUP', 'Group'), ('WITHDRAWAL', 'Withdrawal'), ('WITHDRAWAL_FEE', 'Withdrawal Fee'), ('TRANSACTION_FEE', 'Transaction Fee'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('narration', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('mpesa_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payments.mpesatransaction')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Kenyan number (07XXXXXXXX or 01XXXXXXXX).', regex='^(07|01)\\d{8}$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('source', models.CharField(choices=[('SAVINGS', 'SAVINGS'), ('MERRY', 'MERRY'), ('GROUP', 'GROUP'), ('OTHER', 'OTHER')], db_index=True, default='SAVINGS', max_length=20)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('PROCESSING', 'PROCESSING'), ('PAID', 'PAID'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], db_index=True, default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('mpesa_tx', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='payments.mpesatransaction')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['status', 'channel', 'direction'], name='payments_mp_status_4feae9_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['phone', 'created_at'], name='payments_mp_phone_ec9549_idx'),
        ),
        migrations.AddConstraint(
            model_name='mpesatransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('checkout_request_id__isnull', False), models.Q(('checkout_request_id', ''), _negated=True)), fields=('checkout_request_id',), name='uniq_checkout_request_id'),
        ),
        migrations.AddConstraint(
            model_name='mpesatransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('mpesa_receipt_number__isnull', False), models.Q(('mpesa_receipt_number', ''), _negated=True)), fields=('mpesa_receipt_number',), name='uniq_mpesa_receipt_number'),
        ),
        migrations.AddConstraint(
            model_name='mpesatransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('conversation_id__isnull', False), models.Q(('conversation_id', ''), _negated=True)), fields=('conversation_id',), name='uniq_conversation_id'),
        ),
        migrations.AddIndex(
            model_name='paymentledger',
            index=models.Index(fields=['user', 'created_at'], name='payments_pa_user_id_5c074f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentledger',
            index=models.Index(fields=['category', 'created_at'], name='payments_pa_categor_d5b0be_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentledger',
            index=models.Index(fields=['reference'], name='payments_pa_referen_89297e_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', 'created_at'], name='payments_wi_status_90f0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', 'created_at'], name='payments_wi_user_id_c530c4_idx'),
        ),
    ]
