# Generated by Django 5.2.9 on 2026-03-06 18:10

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('SAVINGS_DEPOSIT', 'Savings Deposit'), ('MERRY_CONTRIBUTION', 'Merry Contribution'), ('GROUP_CONTRIBUTION', 'Group Contribution'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('WITHDRAWAL', 'Withdrawal'), ('OTHER', 'Other')], db_index=True, max_length=40, unique=True)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('percentage_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage applied on base amount, e.g. 2.50 means 2.5%', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction Fee Config',
                'verbose_name_plural': 'Transaction Fee Configs',
                'ordering': ['purpose'],
            },
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original business/base amount before fee.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee portion charged or deducted by backend.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Final amount used for the actual Mpesa transaction.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Requested/base payout amount before fee deduction.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['purpose', 'created_at'], name='payments_mp_purpose_bce169_idx'),
        ),
    ]
