# Generated by Django 5.2.9 on 2026-04-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique STK request id from Safaricom.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='conversation_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique B2C conversation id from Safaricom.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='matched_reference_type',
            field=models.CharField(choices=[('MERRY', 'Merry'), ('SAVINGS', 'Savings'), ('LOAN', 'Loan'), ('GROUP', 'Group'), ('WITHDRAWAL', 'Withdrawal'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', help_text='What type of business reference this transaction matched.', max_length=30),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='origin',
            field=models.CharField(choices=[('APP', 'Started Inside App'), ('EXTERNAL', 'Started Outside App'), ('ADMIN', 'Started by Admin'), ('SYSTEM', 'System Generated')], db_index=True, default='APP', help_text='Where the payment started: app, external/manual, admin, or system.', max_length=30),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='originator_conversation_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='payment_method',
            field=models.CharField(choices=[('STK', 'STK Push'), ('PAYBILL', 'Paybill'), ('TILL', 'Till / Buy Goods'), ('B2C', 'B2C Payout'), ('OTHER', 'Other')], db_index=True, default='STK', help_text='How the payment was made: STK, PAYBILL, TILL, or B2C.', max_length=30),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='result_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout')], db_index=True, default='INITIATED', max_length=30),
        ),
    ]
