# Generated by Django 5.2.9 on 2026-03-01 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesatransaction',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='conversation_id',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='purpose',
            field=models.CharField(choices=[('SAVINGS_DEPOSIT', 'Savings Deposit'), ('MERRY_CONTRIBUTION', 'Merry Contribution'), ('GROUP_CONTRIBUTION', 'Group Contribution'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('WITHDRAWAL', 'Withdrawal'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout')], default='INITIATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentledger',
            name='category',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('LOANS', 'Loans'), ('MERRY', 'Merry-go-round'), ('GROUP', 'Group'), ('WITHDRAWAL', 'Withdrawal'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentledger',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Internal or Mpesa ref, e.g. MPESA receipt / LOAN#12', max_length=120),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='source',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('MERRY', 'Merry-go-round'), ('GROUP', 'Group'), ('OTHER', 'Other')], default='SAVINGS', max_length=20),
        ),
        migrations.AddIndex(
            model_name='paymentledger',
            index=models.Index(fields=['reference'], name='payments_pa_referen_89297e_idx'),
        ),
    ]
