# Generated by Django 5.2.9 on 2026-03-02 19:05

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0002_alter_mpesatransaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='ledger_posted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='channel',
            field=models.CharField(choices=[('STK', 'STK Push'), ('B2C', 'B2C Payout')], default='STK', max_length=10),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, db_index=True, help_text='STK unique ID returned by Safaricom (idempotency key).', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='conversation_id',
            field=models.CharField(blank=True, db_index=True, help_text='B2C unique conversation id returned by Safaricom (idempotency key).', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, db_index=True, help_text='Receipt number for successful transactions (strongest uniqueness).', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Kenyan number (07XXXXXXXX or 01XXXXXXXX).', regex='^(07|01)\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout')], db_index=True, default='INITIATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentledger',
            name='category',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('LOANS', 'Loans'), ('MERRY', 'Merry-go-round'), ('GROUP', 'Group'), ('WITHDRAWAL', 'Withdrawal'), ('WITHDRAWAL_FEE', 'Withdrawal Fee'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentledger',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentledger',
            name='entry_type',
            field=models.CharField(choices=[('CREDIT', 'Credit (Money In)'), ('DEBIT', 'Debit (Money Out)')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentledger',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Kenyan number (07XXXXXXXX or 01XXXXXXXX).', regex='^(07|01)\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='source',
            field=models.CharField(choices=[('SAVINGS', 'SAVINGS'), ('MERRY', 'MERRY'), ('GROUP', 'GROUP'), ('OTHER', 'OTHER')], db_index=True, default='SAVINGS', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('PROCESSING', 'PROCESSING'), ('PAID', 'PAID'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='mpesatransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('checkout_request_id__isnull', False), models.Q(('checkout_request_id', ''), _negated=True)), fields=('checkout_request_id',), name='uniq_checkout_request_id'),
        ),
        migrations.AddConstraint(
            model_name='mpesatransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('mpesa_receipt_number__isnull', False), models.Q(('mpesa_receipt_number', ''), _negated=True)), fields=('mpesa_receipt_number',), name='uniq_mpesa_receipt_number'),
        ),
        migrations.AddConstraint(
            model_name='mpesatransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('conversation_id__isnull', False), models.Q(('conversation_id', ''), _negated=True)), fields=('conversation_id',), name='uniq_conversation_id'),
        ),
    ]
