# Generated by Django 5.2.9 on 2026-04-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_mpesatransaction_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='matched_user_phone',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Registered user phone matched by backend, if any.', max_length=30),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Raw payer/receiver identifier from M-Pesa. For STK/B2C this may be a normal phone number. For C2B v2 it may be an encrypted/hash MSISDN.', max_length=100),
        ),
    ]
