# Generated by Django 5.2.9 on 2026-03-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transactionfeeconfig_mpesatransaction_base_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='channel',
            field=models.CharField(choices=[('STK', 'STK Push'), ('C2B', 'C2B Paybill'), ('B2C', 'B2C Payout')], default='STK', max_length=10),
        ),
    ]
