# Generated by Django 5.2.9 on 2026-03-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_mpesatransaction_ledger_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentledger',
            name='category',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('LOANS', 'Loans'), ('MERRY', 'Merry-go-round'), ('GROUP', 'Group'), ('WITHDRAWAL', 'Withdrawal'), ('WITHDRAWAL_FEE', 'Withdrawal Fee'), ('TRANSACTION_FEE', 'Transaction Fee'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
    ]
