# Generated by Django 5.2.9 on 2026-03-15 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0003_alter_mpesatransaction_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='allocated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_mpesa_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='allocation_notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='allocation_status',
            field=models.CharField(choices=[('UNALLOCATED', 'Unallocated'), ('AUTO_ALLOCATED', 'Auto Allocated'), ('PARTIALLY_ALLOCATED', 'Partially Allocated'), ('MANUAL_REVIEW', 'Manual Review'), ('MANUALLY_ALLOCATED', 'Manually Allocated'), ('INVALID_REFERENCE', 'Invalid Reference')], db_index=True, default='UNALLOCATED', max_length=25),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['allocation_status', 'created_at'], name='payments_mp_allocat_c57870_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['reference', 'channel', 'status'], name='payments_mp_referen_a70bee_idx'),
        ),
    ]
