# Generated by Django 5.2.9 on 2026-03-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_mpesatransaction_allocated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', help_text='Friendly config name, e.g. default or production.', max_length=100, unique=True)),
                ('paybill_number', models.CharField(blank=True, db_index=True, default='', help_text='Manual Paybill number shown to users.', max_length=30)),
                ('business_number', models.CharField(blank=True, db_index=True, default='', help_text='Primary business/short code used for collections.', max_length=30)),
                ('till_number', models.CharField(blank=True, db_index=True, default='', help_text='Optional till number if Buy Goods is enabled.', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this config is active for the system.')),
                ('is_paybill_enabled', models.BooleanField(db_index=True, default=True, help_text='Controls whether manual paybill option is shown/enabled.')),
                ('is_till_enabled', models.BooleanField(db_index=True, default=False, help_text='Controls whether till option is shown/enabled.')),
                ('notes', models.CharField(blank=True, default='', help_text='Optional admin notes.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mpesa Config',
                'verbose_name_plural': 'Mpesa Configs',
                'ordering': ['name'],
            },
        ),
    ]
