# Generated by Django 5.2.9 on 2026-03-20 20:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0005_mpesaconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='callback_received_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the system received the callback or validation result.', null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='external_reference_raw',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Exact account/reference entered by payer outside the app.', max_length=120),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='matched_reference_type',
            field=models.CharField(choices=[('MERRY', 'Merry'), ('SAVINGS', 'Savings'), ('LOAN', 'Loan'), ('GROUP', 'Group'), ('WITHDRAWAL', 'Withdrawal'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', help_text='What type of business reference this transaction matched.', max_length=20),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='matched_user_phone',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Registered user phone matched by backend, if any.', max_length=20),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='origin',
            field=models.CharField(choices=[('APP', 'Started Inside App'), ('EXTERNAL', 'Started Outside App'), ('ADMIN', 'Started by Admin'), ('SYSTEM', 'System Generated')], db_index=True, default='APP', help_text='Where the payment started: app, external/manual, admin, or system.', max_length=20),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='payment_method',
            field=models.CharField(choices=[('STK', 'STK Push'), ('PAYBILL', 'Paybill'), ('TILL', 'Till / Buy Goods'), ('B2C', 'B2C Payout'), ('OTHER', 'Other')], db_index=True, default='STK', help_text='How the payment was made: STK, PAYBILL, TILL, or B2C.', max_length=20),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Final amount actually transacted through M-Pesa.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Business/base amount before fee.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='channel',
            field=models.CharField(choices=[('STK', 'STK Push'), ('C2B', 'C2B Paybill'), ('B2C', 'B2C Payout')], db_index=True, default='STK', max_length=10),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique STK request id from Safaricom.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='conversation_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique B2C conversation id from Safaricom.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='direction',
            field=models.CharField(choices=[('IN', 'Money In'), ('OUT', 'Money Out')], db_index=True, default='IN', max_length=10),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, db_index=True, help_text='Safaricom receipt number for successful transactions.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone',
            field=models.CharField(db_index=True, help_text='Phone used to make or receive the transaction.', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Kenyan number (07XXXXXXXX or 01XXXXXXXX).', regex='^(07|01)\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='purpose',
            field=models.CharField(choices=[('SAVINGS_DEPOSIT', 'Savings Deposit'), ('MERRY_CONTRIBUTION', 'Merry Contribution'), ('GROUP_CONTRIBUTION', 'Group Contribution'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('WITHDRAWAL', 'Withdrawal'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Normalized business reference, e.g. mus11, saving23, loan35, grp9.', max_length=120),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, help_text='Transaction date returned by Safaricom.', null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee amount applied by backend.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Resolved owner/user if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['payment_method', 'origin', 'created_at'], name='payments_mp_payment_c558d4_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['external_reference_raw', 'created_at'], name='payments_mp_externa_8f2f97_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['matched_reference_type', 'created_at'], name='payments_mp_matched_6ac000_idx'),
        ),
    ]
