# Generated by Django 5.2.9 on 2026-03-28 01:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('FLEXIBLE', 'Flexible Savings'), ('FIXED', 'Fixed Savings'), ('TARGET', 'Target-Based Savings')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reserved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('locked_until', models.DateField(blank=True, null=True)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('target_deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('ADJUSTMENT', 'Adjustment'), ('AUTO_DEDUCT', 'Auto Deduction')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='savings.savingsaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='savingsaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='savings_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='savingsaccount',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_amount__gte', 0)), name='savings_reserved_non_negative'),
        ),
        migrations.AddIndex(
            model_name='savingstransaction',
            index=models.Index(fields=['account', 'txn_type', 'created_at'], name='savings_sav_account_e8ab57_idx'),
        ),
        migrations.AddIndex(
            model_name='savingstransaction',
            index=models.Index(fields=['reference'], name='savings_sav_referen_e0dfa6_idx'),
        ),
    ]
