# Generated by Django 5.2.9 on 2026-03-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='account',
        ),
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='reviewed_by',
        ),
        migrations.AddIndex(
            model_name='savingstransaction',
            index=models.Index(fields=['reference'], name='savings_sav_referen_e0dfa6_idx'),
        ),
        migrations.DeleteModel(
            name='WithdrawRequest',
        ),
    ]
