# Generated by Django 5.2.9 on 2026-02-26 19:15

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingsaccount',
            options={'ordering': ['user_id', 'name']},
        ),
        migrations.AlterModelOptions(
            name='savingstransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='withdrawrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='reserved_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddIndex(
            model_name='savingstransaction',
            index=models.Index(fields=['account', 'txn_type', 'created_at'], name='savings_sav_account_e8ab57_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawrequest',
            index=models.Index(fields=['status', 'created_at'], name='savings_wit_status_78c16b_idx'),
        ),
        migrations.AddConstraint(
            model_name='savingsaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='savings_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='savingsaccount',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_amount__gte', 0)), name='savings_reserved_non_negative'),
        ),
    ]
