# Generated by Django 5.2.9 on 2025-12-23 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_status_alter_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(default=36459535, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_photo', models.ImageField(upload_to='kyc/passport/')),
                ('id_front', models.ImageField(upload_to='kyc/id_front/')),
                ('id_back', models.ImageField(upload_to='kyc/id_back/')),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
