# Generated by Django 5.2.9 on 2026-03-03 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_otp_phone_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Name can contain letters, spaces, hyphens, and apostrophes only', regex="^[A-Za-z\\s'-]+$")]),
        ),
    ]
