# Generated by Django 5.2.9 on 2026-03-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_otp_attempts_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycprofile',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
    ]
