# Generated by Django 5.2.9 on 2026-03-28 01:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('group_type', models.CharField(choices=[('BURIAL', 'Burial/Welfare'), ('WEDDING', 'Wedding'), ('EDUCATION', 'Education/School Fees'), ('INVESTMENT', 'Investment'), ('SAVINGS', 'Savings'), ('EMERGENCY', 'Emergency Support'), ('DEVELOPMENT', 'Community Development'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('objective', models.CharField(blank=True, default='', max_length=255)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20)),
                ('join_policy', models.CharField(choices=[('OPEN', 'Open'), ('APPROVAL', 'Approval Required'), ('CLOSED', 'Closed')], default='APPROVAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('max_members', models.PositiveIntegerField(default=0, help_text='0 means unlimited members')),
                ('requires_contributions', models.BooleanField(default=False)),
                ('contribution_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('contribution_frequency', models.CharField(blank=True, default='', help_text='Example: WEEKLY, MONTHLY, ONCE, ADHOC', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GroupContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank'), ('OTHER', 'Other')], default='MANUAL', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reserved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fund', to='groups.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='groups.group')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_group_join_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GroupMemberShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_contributed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reserved_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_shares', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Admin'), ('TREASURER', 'Treasurer'), ('SECRETARY', 'Secretary')], default='MEMBER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GroupShareHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_holds', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_share_holds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['group_type', 'is_active'], name='groups_grou_group_t_4c713a_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['join_policy', 'is_active'], name='groups_grou_join_po_b4de00_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['visibility', 'is_active'], name='groups_grou_visibil_863359_idx'),
        ),
        migrations.AddIndex(
            model_name='groupcontribution',
            index=models.Index(fields=['group', 'user', 'created_at'], name='groups_grou_group_i_226b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupcontribution',
            index=models.Index(fields=['reference'], name='groups_grou_referen_7c8546_idx'),
        ),
        migrations.AddIndex(
            model_name='groupcontribution',
            index=models.Index(fields=['source', 'created_at'], name='groups_grou_source_7f44a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupfund',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='groupfund_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='groupfund',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_amount__gte', 0)), name='groupfund_reserved_non_negative'),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['group', 'status', 'created_at'], name='groups_grou_group_i_bb13d3_idx'),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['user', 'status', 'created_at'], name='groups_grou_user_id_2ea16b_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('group', 'user'), name='uniq_pending_group_join_request_per_user'),
        ),
        migrations.AddIndex(
            model_name='groupmembershare',
            index=models.Index(fields=['group', 'user'], name='groups_grou_group_i_eadea5_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmembershare',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='uniq_group_member_share'),
        ),
        migrations.AddConstraint(
            model_name='groupmembershare',
            constraint=models.CheckConstraint(condition=models.Q(('total_contributed__gte', 0)), name='groupshare_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='groupmembershare',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_share__gte', 0)), name='groupshare_reserved_non_negative'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'is_active'], name='groups_grou_group_i_f7e3a8_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user', 'is_active'], name='groups_grou_user_id_bd45cf_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'role'], name='groups_grou_group_i_0277c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='uniq_group_user_membership'),
        ),
        migrations.AddIndex(
            model_name='groupsharehold',
            index=models.Index(fields=['group', 'user', 'loan_id', 'is_active'], name='groups_grou_group_i_a879a5_idx'),
        ),
    ]
