# Generated by Django 5.2.9 on 2026-04-02 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='payment_code',
            field=models.CharField(blank=True, help_text='Unique letters-only code used in manual payment references, e.g. UN, WF, MG.', max_length=10, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['payment_code'], name='groups_grou_payment_6b107b_idx'),
        ),
    ]
