# Generated by Django 5.2.9 on 2026-04-18 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_payment_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDependant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('SIBLING', 'Sibling'), ('PARENT', 'Parent'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependants', to='groups.groupmembership')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['membership', 'is_active'], name='groups_grou_members_e670be_idx'), models.Index(fields=['relationship', 'is_active'], name='groups_grou_relatio_1b756f_idx')],
                'constraints': [models.UniqueConstraint(fields=('membership', 'name', 'relationship'), name='uniq_membership_dependant_name_relationship')],
            },
        ),
    ]
