# Generated by Django 5.2.9 on 2026-03-14 00:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupcontribution_groupfund_groupmembershare_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='groupmembershare',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='group',
            name='contribution_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='group',
            name='contribution_frequency',
            field=models.CharField(blank=True, default='', help_text='Example: WEEKLY, MONTHLY, ONCE, ADHOC', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='groups_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('BURIAL', 'Burial/Welfare'), ('WEDDING', 'Wedding'), ('EDUCATION', 'Education/School Fees'), ('INVESTMENT', 'Investment'), ('SAVINGS', 'Savings'), ('EMERGENCY', 'Emergency Support'), ('DEVELOPMENT', 'Community Development'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='join_policy',
            field=models.CharField(choices=[('OPEN', 'Open'), ('APPROVAL', 'Approval Required'), ('CLOSED', 'Closed')], default='APPROVAL', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='max_members',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited members'),
        ),
        migrations.AddField(
            model_name='group',
            name='objective',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='requires_contributions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='group',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20),
        ),
        migrations.AddField(
            model_name='groupcontribution',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank'), ('OTHER', 'Other')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Admin'), ('TREASURER', 'Treasurer'), ('SECRETARY', 'Secretary')], default='MEMBER', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['group_type', 'is_active'], name='groups_grou_group_t_4c713a_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['join_policy', 'is_active'], name='groups_grou_join_po_b4de00_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['visibility', 'is_active'], name='groups_grou_visibil_863359_idx'),
        ),
        migrations.AddIndex(
            model_name='groupcontribution',
            index=models.Index(fields=['source', 'created_at'], name='groups_grou_source_7f44a7_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembershare',
            index=models.Index(fields=['group', 'user'], name='groups_grou_group_i_eadea5_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'is_active'], name='groups_grou_group_i_f7e3a8_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user', 'is_active'], name='groups_grou_user_id_bd45cf_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'role'], name='groups_grou_group_i_0277c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmembershare',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='uniq_group_member_share'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='uniq_group_user_membership'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_group_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['group', 'status', 'created_at'], name='groups_grou_group_i_bb13d3_idx'),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['user', 'status', 'created_at'], name='groups_grou_user_id_2ea16b_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('group', 'user'), name='uniq_pending_group_join_request_per_user'),
        ),
    ]
