from decimal import Decimal, InvalidOperation

from django.core.validators import RegexValidator
from rest_framework import serializers

from .models import (
    MpesaConfig,
    MpesaTransaction,
    PaymentLedger,
    TransactionFeeConfig,
    WithdrawalRequest,
)


# =========================================================
# Shared validators / helpers
# =========================================================
phone_validator = RegexValidator(
    regex=r"^(07|01)\d{8}$",
    message="Phone number must be a valid Kenyan number (07XXXXXXXX or 01XXXXXXXX).",
)


def _money(v) -> Decimal:
    try:
        return Decimal(str(v))
    except (InvalidOperation, TypeError, ValueError):
        return Decimal("0.00")


def _normalize_phone(value: str) -> str:
    v = (value or "").strip().replace(" ", "").replace("-", "")
    if v.startswith("+254"):
        v = "0" + v[4:]
    elif v.startswith("254"):
        v = "0" + v[3:]
    return v


# =========================================================
# Mpesa Config
# =========================================================
class MpesaConfigSerializer(serializers.ModelSerializer):
    """
    Central payment channel config serializer.

    Frontend should use this for:
    - paybill number
    - business number
    - till number
    - enable/disable flags

    Account references are generated by business logic elsewhere.
    Current reference standard:
    - mus19    -> merry contribution for user id 19
    - saving19 -> savings deposit for user id 19
    - loan19   -> loan repayment for user id 19
    - grp9     -> group contribution for group id 9
    """

    class Meta:
        model = MpesaConfig
        fields = [
            "id",
            "name",
            "paybill_number",
            "business_number",
            "till_number",
            "is_active",
            "is_paybill_enabled",
            "is_till_enabled",
            "notes",
            "updated_at",
        ]
        read_only_fields = [
            "id",
            "updated_at",
        ]

    def validate_name(self, value):
        value = (value or "").strip()
        if not value:
            raise serializers.ValidationError("Name is required.")
        return value

    def validate_paybill_number(self, value):
        return (value or "").strip()

    def validate_business_number(self, value):
        return (value or "").strip()

    def validate_till_number(self, value):
        return (value or "").strip()

    def validate_notes(self, value):
        return (value or "").strip()


# =========================================================
# Fee Config
# =========================================================
class TransactionFeeConfigSerializer(serializers.ModelSerializer):
    class Meta:
        model = TransactionFeeConfig
        fields = [
            "id",
            "purpose",
            "fixed_fee",
            "percentage_fee",
            "is_active",
            "updated_at",
        ]
        read_only_fields = ["id", "updated_at"]

    def validate_fixed_fee(self, value):
        if value is None:
            return Decimal("0.00")
        if value < Decimal("0.00"):
            raise serializers.ValidationError("Fixed fee cannot be negative.")
        return value

    def validate_percentage_fee(self, value):
        if value is None:
            return Decimal("0.00")
        if value < Decimal("0.00"):
            raise serializers.ValidationError("Percentage fee cannot be negative.")
        if value > Decimal("100.00"):
            raise serializers.ValidationError("Percentage fee cannot exceed 100.")
        return value


# =========================================================
# Mpesa Transaction (STK / C2B / B2C)
# =========================================================
class MpesaTransactionSerializer(serializers.ModelSerializer):
    user_id = serializers.IntegerField(source="user.id", read_only=True)
    allocated_by_id = serializers.IntegerField(source="allocated_by.id", read_only=True)

    class Meta:
        model = MpesaTransaction
        fields = [
            "id",
            "user_id",
            "phone",
            "matched_user_phone",
            "amount",
            "base_amount",
            "transaction_fee",
            # include this only if it exists on your model
            # "requested_amount",
            "direction",
            "channel",
            "payment_method",
            "origin",
            "purpose",
            "status",
            "reference",
            "external_reference_raw",
            "matched_reference_type",
            "merchant_request_id",
            "checkout_request_id",
            "conversation_id",
            "originator_conversation_id",
            "result_code",
            "result_desc",
            "mpesa_receipt_number",
            "transaction_date",
            "callback_received_at",
            "request_payload",
            "callback_payload",
            "ledger_posted",
            "allocation_status",
            "allocation_notes",
            "allocated_by_id",
            "allocated_at",
            "created_at",
            "updated_at",
        ]
        read_only_fields = [
            "id",
            "user_id",
            "matched_user_phone",
            "direction",
            "channel",
            "payment_method",
            "origin",
            "purpose",
            "status",
            "reference",
            "external_reference_raw",
            "matched_reference_type",
            "merchant_request_id",
            "checkout_request_id",
            "conversation_id",
            "originator_conversation_id",
            "result_code",
            "result_desc",
            "mpesa_receipt_number",
            "transaction_date",
            "callback_received_at",
            "request_payload",
            "callback_payload",
            "ledger_posted",
            "allocation_status",
            "allocation_notes",
            "allocated_by_id",
            "allocated_at",
            "created_at",
            "updated_at",
        ]


# =========================================================
# Ledger
# =========================================================
class PaymentLedgerSerializer(serializers.ModelSerializer):
    mpesa_tx = MpesaTransactionSerializer(read_only=True)

    class Meta:
        model = PaymentLedger
        fields = [
            "id",
            "entry_type",
            "category",
            "amount",
            "narration",
            "reference",
            "mpesa_tx",
            "created_at",
        ]
        read_only_fields = fields


# =========================================================
# Withdrawal
# =========================================================
class WithdrawalSerializer(serializers.ModelSerializer):
    mpesa_tx = MpesaTransactionSerializer(read_only=True)
    user_id = serializers.IntegerField(source="user.id", read_only=True)
    approved_by_id = serializers.IntegerField(source="approved_by.id", read_only=True)
    rejected_by_id = serializers.IntegerField(source="rejected_by.id", read_only=True)
    is_final = serializers.BooleanField(read_only=True)
    can_withdraw_merry = serializers.BooleanField(read_only=True)

    class Meta:
        model = WithdrawalRequest
        fields = [
            "id",
            "user_id",
            "phone",
            "amount",
            "source",
            "status",
            "approved_by_id",
            "approved_at",
            "rejected_by_id",
            "rejected_at",
            "rejection_reason",
            "mpesa_tx",
            "is_final",
            "can_withdraw_merry",
            "created_at",
            "updated_at",
        ]
        read_only_fields = fields


class WithdrawalCreateSerializer(serializers.ModelSerializer):
    phone = serializers.CharField(validators=[phone_validator])

    class Meta:
        model = WithdrawalRequest
        fields = [
            "phone",
            "amount",
            "source",
        ]

    def validate_phone(self, value):
        value = _normalize_phone(value)
        phone_validator(value)
        return value

    def validate_amount(self, value):
        if value is None or value <= Decimal("0.00"):
            raise serializers.ValidationError("Amount must be greater than 0.")
        return value

    def validate_source(self, value):
        value = (value or "SAVINGS").upper()
        allowed = {
            c[0] if isinstance(c, tuple) else c
            for c in WithdrawalRequest._meta.get_field("source").choices
        }
        if value not in allowed:
            raise serializers.ValidationError(
                f"Invalid source. Choose from: {sorted(allowed)}"
            )
        return value

    def create(self, validated_data):
        request = self.context["request"]
        return WithdrawalRequest.objects.create(
            user=request.user,
            phone=validated_data["phone"],
            amount=validated_data["amount"],
            source=validated_data.get("source", "SAVINGS"),
            status="PENDING",
        )


class WithdrawalApproveSerializer(serializers.Serializer):
    """
    Kept intentionally light.
    Add optional admin fields later if needed.
    """
    note = serializers.CharField(required=False, allow_blank=True, max_length=255)


class WithdrawalRejectSerializer(serializers.Serializer):
    rejection_reason = serializers.CharField(
        required=True,
        allow_blank=False,
        max_length=255,
    )